# Generated by Django 3.2.6 on 2021-09-21 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_received_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='Customer Name', max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 27, 132028))),
                ('serial_number', models.CharField(default='Serial Number', max_length=400)),
                ('category', models.CharField(default='category', max_length=400)),
                ('subcategory', models.CharField(default='subcategory', max_length=400)),
                ('condition', models.CharField(choices=[('Fair', 'Fair'), ('new', 'new'), ('old', 'old')], default='condition', max_length=400)),
                ('comments', models.TextField(default='comment', max_length=400)),
                ('quantity', models.IntegerField(default='Quantity')),
                ('description', models.CharField(default='Description', max_length=300)),
                ('order_no', models.CharField(default='Order No.', max_length=200)),
                ('stores_no', models.CharField(default='Stores No', max_length=300)),
                ('unit_cost', models.CharField(default="Unit Cost'", max_length=300)),
                ('ordered_by', models.CharField(default='Ordered By', max_length=300)),
                ('received_by', models.CharField(default='Received By', max_length=300)),
                ('checked_by', models.CharField(default='Checked by', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('Pid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Producttable',
            },
        ),
        migrations.CreateModel(
            name='Issue_receipt_voucher',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.goods_received_note')),
                ('site_name', models.CharField(default='Site Name', max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 27, 132278))),
                ('stores_request_no', models.CharField(default='Stores Req. No', max_length=300)),
                ('quantity', models.IntegerField(default='Quantity')),
                ('issued_by', models.CharField(default='Issued By', max_length=300)),
                ('issuere_title', models.CharField(default='Issuer Title', max_length=300)),
                ('approved_by', models.CharField(default='Approved By', max_length=300)),
                ('approver_title', models.CharField(default='Approver Title', max_length=300)),
                ('ferried_by', models.CharField(default='Ferried by', max_length=300)),
                ('ferrier_title', models.CharField(default='Ferrier Title', max_length=300)),
                ('received_by', models.CharField(default='Received By', max_length=300)),
                ('receiver_title', models.CharField(default='Receiver Title', max_length=300)),
                ('stock_entered_by', models.CharField(default='Stock Entered By', max_length=300)),
                ('stock_enterer_title', models.CharField(default='Stock Enterer Title', max_length=300)),
                ('destination', models.CharField(default='Destination', max_length=300)),
                ('comments', models.TextField(default='Comments', max_length=300)),
                ('customer1', models.CharField(default='Customer Name', max_length=300)),
                ('date1', models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 27, 132348))),
                ('serial_number1', models.CharField(default='Serial Number', max_length=400)),
                ('category1', models.CharField(default='category', max_length=400)),
                ('subcategory1', models.CharField(default='subcategory', max_length=400)),
                ('condition1', models.CharField(choices=[('Fair', 'Fair'), ('new', 'new'), ('old', 'old')], default='condition', max_length=400)),
                ('comments1', models.TextField(default='comment', max_length=400)),
                ('quantity1', models.IntegerField(default='Quantity')),
                ('description1', models.CharField(default='Description', max_length=300)),
                ('order_no1', models.CharField(default='Order No.', max_length=200)),
                ('stores_no1', models.CharField(default='Stores No', max_length=300)),
                ('unit_cost1', models.CharField(default="Unit Cost'", max_length=300)),
                ('ordered_by1', models.CharField(default='Ordered By', max_length=300)),
                ('received_by1', models.CharField(default='Received By', max_length=300)),
                ('checked_by1', models.CharField(default='Checked by', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('Itemid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Itemname', models.CharField(max_length=200)),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productmodel')),
            ],
            options={
                'db_table': 'Itemstable',
            },
        ),
    ]
