# Generated by Django 3.2.6 on 2021-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_received_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='Customer Name', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.CharField(default='Quantity', max_length=400)),
                ('description', models.CharField(default='Description', max_length=300)),
                ('order_no', models.CharField(default='Order No.', max_length=200)),
                ('stores_no', models.CharField(default='Stores No', max_length=300)),
                ('unit_cost', models.CharField(default="Unit Cost'", max_length=300)),
                ('ordered_by', models.CharField(default='Ordered By', max_length=300)),
                ('received_by', models.CharField(default='Received By', max_length=300)),
                ('checked_by', models.CharField(default="Checked by'", max_length=300)),
            ],
        ),
    ]
