# Generated by Django 3.2.6 on 2021-09-21 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 41, 202435)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 41, 202706)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date1',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 14, 7, 41, 202774)),
        ),
    ]
