# Generated by Django 3.2.6 on 2021-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_receipt_voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('stores_request_no', models.CharField(default='Stores Req. No', max_length=300)),
                ('request_description', models.CharField(default='Request Description', max_length=300)),
                ('unit', models.CharField(default='Unit', max_length=300)),
                ('quantity', models.CharField(default='Quantity', max_length=400)),
                ('issued_by', models.CharField(default='Issued By', max_length=300)),
                ('issuere_title', models.CharField(default='Issuer Title', max_length=300)),
                ('approved_by', models.CharField(default='Approved By', max_length=300)),
                ('approver_title', models.CharField(default='Approver Title', max_length=300)),
                ('ferried_by', models.CharField(default='Ferried by', max_length=300)),
                ('ferrier_title', models.CharField(default='Ferrier Title', max_length=300)),
                ('received_by', models.CharField(default='Received By', max_length=300)),
                ('receiver_title', models.CharField(default='Receiver Title', max_length=300)),
                ('stock_entered_by', models.CharField(default='Stock Entered By', max_length=300)),
                ('stock_enterer_title', models.CharField(default='Stock Enterer Title', max_length=300)),
                ('destination', models.CharField(default='Destination', max_length=300)),
                ('comments', models.TextField(default='Comments', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='goods_received_note',
            name='checked_by',
            field=models.CharField(default='Checked by', max_length=300),
        ),
    ]
