# Generated by Django 3.2.6 on 2021-09-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210915_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_received_note',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Chair', 'Chair'), ('Stationery', 'Stationery'), ('Motorbike', 'Motorbike')], default='category', max_length=400),
        ),
        migrations.AddField(
            model_name='goods_received_note',
            name='condition',
            field=models.CharField(choices=[('Fair', 'Fair'), ('new', 'new'), ('old', 'old')], default='condition', max_length=400),
        ),
        migrations.AddField(
            model_name='goods_received_note',
            name='serial_number',
            field=models.CharField(default='Serial Number', max_length=400),
        ),
    ]
