# Generated by Django 3.2.6 on 2021-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210916_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('Itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('Itemname', models.CharField(max_length=200)),
                ('Pid', models.IntegerField()),
            ],
            options={
                'db_table': 'Itemstable',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Producttable',
            },
        ),
    ]
