# Generated by Django 3.2.6 on 2021-09-22 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210922_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_received_note',
            name='issued',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 46, 53, 482965)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 46, 53, 483222)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date1',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 46, 53, 483291)),
        ),
    ]
