# Generated by Django 3.2.6 on 2021-09-22 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210922_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 47, 3, 629857)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 47, 3, 630115)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date1',
            field=models.DateField(default=datetime.datetime(2021, 9, 22, 8, 47, 3, 630184)),
        ),
    ]
