# Generated by Django 3.2.6 on 2021-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210916_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table=None,
        ),
    ]
