# Generated by Django 3.2.6 on 2021-09-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210916_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmodel',
            table='Itemstable',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='Producttable',
        ),
    ]
