# Generated by Django 3.2.6 on 2021-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210916_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='Itemid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Pid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
