# Generated by Django 3.2.6 on 2021-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_goods_received_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_received_note',
            name='subcategory',
            field=models.CharField(default='subcategory', max_length=400),
        ),
    ]
