# Generated by Django 3.2.6 on 2021-09-17 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_goods_received_note_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 10, 22, 10, 632288)),
        ),
    ]
