# Generated by Django 3.2.6 on 2021-09-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_goods_received_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 10, 50, 26, 936572)),
        ),
    ]
