# Generated by Django 3.2.6 on 2021-09-18 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_goods_received_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_received_note',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 2, 39, 53, 798655)),
        ),
        migrations.AlterField(
            model_name='issue_receipt_voucher',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 2, 39, 53, 798895)),
        ),
    ]
